version: '3.8'
services:
  aggregator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-u", "scripts/publisher.py", "--url", "http://aggregator:8080/publish", "--count", "5000", "--dup_ratio", "0.2", "--batch_size", "200"]
    depends_on:
      - aggregator

volumes:
  data:
